---
- name: Создание пользователя с SSH ключем
  hosts: all
  become: yes
  gather_facts: yes
  
  vars:
    username: ""
    ssh_public_key: ""
    sudo_access: false
    ssh_config_dir: "/etc/ssh/sshd_config.d"
    
  tasks:
    - name: Валидация username
      ansible.builtin.fail:
        msg: "Некоректный username"
      when: username is not match("^[a-z][-a-z0-9]*$")
      
    - name: Проверка есть ли уже пользователь в система
      getent:
        database: passwd
        key: "{{ username }}"
      register: user_exists
      failed_when: false
      
    - name: Ошибка если пользователь есть
      fail:
        msg: "пользователь '{{ username }}' уже есть"
      when: user_exists.ansible_facts.getent_passwd[username] is defined
      
    - name: Создание пользователя без возможности авторизации пароля
      user:
        name: "{{ username }}"
        shell: /bin/bash
        create_home: yes
        password_lock: yes
        state: present
      register: user_creation
      
    - name: Пользователь создан
      debug:
        msg: "Пользователь '{{ username }}' создан успешно (авторизация по паролю отключена)"
      when: user_creation is succeeded
      
    - name: Создание .ssh директории
      file:
        path: "/home/{{ username }}/.ssh"
        state: directory
        owner: "{{ username }}"
        group: "{{ username }}"
        mode: '0700'
        
    - name: Создание файла authorized_keys для пользователя
      copy:
        content: "{{ ssh_public_key }}"
        dest: "/home/{{ username }}/.ssh/authorized_keys_{{ username }}"
        owner: "{{ username }}"
        group: "{{ username }}"
        mode: '0600'
        
    - name: Создание основного файла authorized_keys с заголовко
      copy:
        content: "{{ ssh_public_key }}"
        dest: "/home/{{ username }}/.ssh/authorized_keys"
        owner: "{{ username }}"
        group: "{{ username }}"
        mode: '0600'
        
    - name: Вывод информации о SSH ключе
      debug:
        msg: "SSH ключ был добавлен в: /home/{{ username }}/.ssh/authorized_keys_{{ username }}"
        
    - name: Генерация случайного пароля для доступа sudo
      set_fact:
        generated_password: "{{ lookup('password', '/dev/null length=16 chars=ascii_letters,digits') }}"
      when: sudo_access | bool
      
    - name: Установка пароля пользователя для sudo доступ
      user:
        name: "{{ username }}"
        password: "{{ generated_password | password_hash }}"
      when: sudo_access | bool
      
    - name: Добавление пользователя в группу sudo
      user:
        name: "{{ username }}"
        groups: sudo
        append: yes
      when: sudo_access | bool
      
    - name: Вывод информации о предоставлении sudo доступа
      debug:
        msg: "Пользователю '{{ username }}' предоставлен доступ sudo (требуется пароль)"
      when: sudo_access | bool
      
    - name: Вывод информации об отсутствии sudo доступа
      debug:
        msg: "Пользователю не предоставлен sudo доступ"
      when: not (sudo_access | bool)
      
    - name: Создание директории конфигурации SSH
      file:
        path: "{{ ssh_config_dir }}"
        state: directory
        mode: '0755'
        
    - name: Создание конфигурационного SSH-файла для пользователя
      copy:
        content: |
          Match User {{ username }}
              PasswordAuthentication no
              PubkeyAuthentication yes
              AuthenticationMethods publickey
              MaxAuthTries 9
        dest: "{{ ssh_config_dir }}/user_{{ username }}.conf"
        mode: '0644'
      notify: reload_ssh
      
    - name: Вывод информации о создании SSH конфигурации
      debug:
        msg: "Создан файл конфигурации SSH: {{ ssh_config_dir }}/user_{{ username }}.conf"
        
  handlers:
    - name: reload_ssh
      ansible.builtin.systemd:
        name: sshd
        state: reloaded
      ignore_errors: yes

    - name: Вывод информации о перезагрузке SSH службы
      debug:
        msg:  "SSH был перезагружен"

        
  post_tasks:
    - name: Completed
      debug:
        msg: |
          Имя пользователя: {{ username }}
          Пароль: {{ generated_password | default('НЕТ') }}
          SSH ключ сохранен в: /home/{{ username }}/.ssh/authorized_keys_{{ username }}
          Sudo доступ: {{ sudo_access }}
          Аутентификация: только по SSH ключу (пароль отключен)