---
- name: Установка Docker на Ubuntu
  hosts: hosts
  become: true

  tasks:
    - name: Установка зависимостей
      apt:
        name:
          - apt-transport-https
          - ca-certificates
          - curl
          - software-properties-common
        state: present
        update_cache: yes

    - name: Добавление GPG-ключа Docker
      apt_key:
        url: https://download.docker.com/linux/ubuntu/gpg
        state: present

    - name: Добавление репозитория Docker
      apt_repository:
        repo: deb [arch=amd64] https://download.docker.com/linux/ubuntu focal stable
        state: present
        filename: docker

    - name: Установка Docker
      apt:
        name: docker-ce
        state: latest
        update_cache: yes

    - name: Убедиться, что Docker запущен и включен
      systemd:
        name: docker
        enabled: true
        state: started
